In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,33,54,4],[4,3,4,5,6,65]])
print(a.ndim,b.ndim)
print(a.size,b.size) #for using size, if it is 2-D array, both arrays should be of same size

1 2
5 12


In [3]:
a=np.arange(1,110,20) #start,stop,increment
print(a)

[  1  21  41  61  81 101]


In [4]:
c=np.random.rand(2,3) #to make matrix of random numbers, 2by3 matrix
print(c)
print(c.ndim)   

[[0.82744677 0.15322839 0.91516737]
 [0.42907085 0.33271922 0.35960215]]
2


In [5]:
#Making something an array
D=np.arange(1,101)
print(D)
print()

D=D.reshape(10,10)    #make this into matrix of 10by10
# D=np.arange(100).reshape(5,20)
print(D)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [6]:
#Use copy to create a copy
a=np.arange(100)
b=a[3:10]
print(b)
b[0]=345
print(b)
print(a[1:10]) #Here we see even a has been changed

print()

a2=np.arange(100)
b2=a2[3:10].copy()
b2[0]=345
print(b2)
print(a2[1:10])

[3 4 5 6 7 8 9]
[345   4   5   6   7   8   9]
[  1   2 345   4   5   6   7   8   9]

[345   4   5   6   7   8   9]
[1 2 3 4 5 6 7 8 9]


In [7]:
b2=np.array([1,2,3,4,23,7,4,3,2,1,4,5])
print(np.where(b2==7))
print(np.where(a2==7))

(array([5], dtype=int64),)
(array([7], dtype=int64),)


In [8]:
A1=np.round(10*np.random.rand(2,1),2)  #2 decimals
A2=np.round(10*np.random.rand(5,4))    #no decimals
A3=np.random.rand(5,4)
# A4=np.round(np.random.rand(5,4),3)
print(A1)
print()
print(A2)
print()
print(A3)
# print()
# print(A4)


[[9.86]
 [6.13]]

[[6. 1. 5. 8.]
 [6. 3. 4. 3.]
 [6. 1. 7. 3.]
 [6. 3. 3. 3.]
 [3. 7. 6. 4.]]

[[0.97315539 0.17850652 0.00385186 0.23475252]
 [0.32647227 0.14931073 0.85192377 0.20915394]
 [0.58475451 0.2044273  0.63795655 0.68144152]
 [0.40435942 0.15159569 0.31444896 0.71606447]
 [0.6712669  0.9922783  0.04094713 0.40660839]]


In [9]:
a=np.array([
    [1,2,3,76,43],
    [7,97,43,70,6],
    [7,5,9,3,5],
    [9,3,4,667,2]
    ])
print(a[2:,0:3])

[[7 5 9]
 [9 3 4]]


In [10]:
# np.sort(a)  pura array sort kardega
print('Normal Array')
print(a,'\n')
print('Sorted Along rows, axis=1')
print(np.sort(a,axis=1),'\n') #return sorted copy of array, along rows
print('Sorted Along coloumns, axis=0')
print(np.sort(a,axis=0)) #along coloumns

Normal Array
[[  1   2   3  76  43]
 [  7  97  43  70   6]
 [  7   5   9   3   5]
 [  9   3   4 667   2]] 

Sorted Along rows, axis=1
[[  1   2   3  43  76]
 [  6   7  43  70  97]
 [  3   5   5   7   9]
 [  2   3   4   9 667]] 

Sorted Along coloumns, axis=0
[[  1   2   3   3   2]
 [  7   3   4  70   5]
 [  7   5   9  76   6]
 [  9  97  43 667  43]]


In [11]:
print(a,'\n')
B=a[a>40] #B will have all elements of a which are greater than 40
print(B,'\n')
# B.sort()
# print(B) printing sorted copy of elements of B

# B=a[(a>40) and (a<120)] This will not work as 'and' is not useful here
B=a[(a>40) & (a<120)] #Having more than one arguments for selecting elements of B
print(B)

[[  1   2   3  76  43]
 [  7  97  43  70   6]
 [  7   5   9   3   5]
 [  9   3   4 667   2]] 

[ 76  43  97  43  70 667] 

[76 43 97 43 70]


In [12]:
c=a[2:4,2:4]
print(c,'\n')
z=np.arange(2)
# print(z)
print(z.reshape(2,1),'\n')
print(c+z.reshape(2,1))

[[  9   3]
 [  4 667]] 

[[0]
 [1]] 

[[  9   3]
 [  5 668]]


In [53]:
import numpy as np
b=np.random.rand(10**2)
# print(b)
%timeit sum(b)
# # print(c)
%timeit np.sum(b)
# # print(d)

26.2 µs ± 2.69 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
12.2 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [54]:
b=np.random.rand(10**8)
%timeit np.amin(b)
# %timeit np.amax(b)

def smallest(i):
    small=b[0]
    for pqrs in i:
        if pqrs<small:small=pqrs
    return pqrs
%timeit smallest(b)

84.8 ms ± 3.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
20.4 s ± 1.07 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
